### ISSUE TITLE
How about average temperature?

### ISSUE THREAD

**Issue by ogencoglu** [imantsm/COVID-19#3]
There is min and max temperature but how about average temperature? Mean of min and max may or may not correspond to daily average.

**Comment by imantsm** [comment]
The API that I use for the weather data does not have an average temperature field, unfortunately. 

The following is a sample for the data that are returned for a given longitude, latitude, and time:

---
{'time': 1577811600,
 'summary': 'Mostly cloudy throughout the day.',
 'icon': 'partly-cloudy-day',
 'sunriseTime': 1577835780,
 'sunsetTime': 1577876280,
 'moonPhase': 0.2,
 'precipIntensity': 0.0017,
 'precipIntensityMax': 0.0062,
 'precipIntensityMaxTime': 1577868720,
 'precipProbability': 0.05,
 'precipType': 'rain',
 'temperatureHigh': 33.41,
 'temperatureHighTime': 1577861580,
 'temperatureLow': 22.35,
 'temperatureLowTime': 1577916600,
 'apparentTemperatureHigh': 34.75,
 'apparentTemperatureHighTime': 1577861940,
 'apparentTemperatureLow': 23.13,
 'apparentTemperatureLowTime': 1577916600,
 'dewPoint': 19.57,
 'humidity': 0.62,
 'pressure': 1016.6,
 'windSpeed': 4.71,
 'windGust': 12.33,
 'windGustTime': 1577819580,
 'windBearing': 69,
 'cloudCover': 0.71,
 'uvIndex': 6,
 'uvIndexTime': 1577857380,
 'visibility': 16.093,
 'ozone': 246.7,
 'temperatureMin': 22.88,
 'temperatureMinTime': 1577830020,
 'temperatureMax': 33.41,
 'temperatureMaxTime': 1577861580,
 'apparentTemperatureMin': 23.54,
 'apparentTemperatureMinTime': 1577830020,
 'apparentTemperatureMax': 34.75,
 'apparentTemperatureMaxTime': 1577861940}

---

Based on nothing more than my own intuition, I took the values that I assumed to be the most relevant or actionable. 

Dark Sky, whose API I have been using, was bought by Apple a few months ago. I think that as a Joe Blow, my API access is going to be cut off in a year or two. If you know of a similarly easy-to-use and affordable API that is available and that has the data points that you're looking for, I'd be happy to give them a whirl.
