### ISSUE TITLE
Units of the measurements in readme

### ISSUE THREAD

**Issue by ogencoglu** [imantsm/COVID-19#4]
Would be great if the units can be added to readme. It is hard to infer what settings have been used for the API calls. For example humidity looks way too high to be  g/m3. I had to find out that it is not humidity actually, it is relative humidity. It would be great to have these clarifications in readme.

**Comment by imantsm** [comment]
I'll try to make some clarifications with my next update that I push, which will hopefully be soon. Thanks for bringing this to my attention.
